export default {

    /********************* BottomTabs  Icons **********************/ 
    // firstActiveIcon: require('../assets/images/ic_red_add.png'),
    // firstInActiveIcon: require('../assets/images/ic_home.png'),
    // secondActiveIcon: require('../assets/images/ic_srch.png'),
    // secondInActiveIcon: require('../assets/images/ic_srch.png'),
    // thirdActiveIcon: require('../assets/images/ic_red_add.png'),
    // thirdInActiveIcon: require('../assets/images/ic_red_add.png'),
    // fourthActiveIcon: require('../assets/images/ic_notify.png'),
    // fourthInActiveIcon: require('../assets/images/ic_notify.png'),
    // fifthActiveIcon: require('../assets/images/ic_user.png'),
    // fifthInActiveIcon: require('../assets/images/ic_user.png'),
    
    /********************* App  Icons **********************/ 
    // icLogo: require('../assets/images/logo.png'),
    // icGoogle: require('../assets/images/activeHeart.png'),
    // icFacebook: require('../assets/images/ic_facebook.png'),
    // icApple: require('../assets/images/ic_apple.png'),
    // icBack: require('../assets/images/ic_back_arrow.png'),
    // icCheck: require('../assets/images/ic_blue_tick.png'),
    // icUnchek: require('../assets/images/ic_grey_tick.png'),
    // icShare: require('../assets/images/ic_direction.png'),
    // icDots: require('../assets/images/ic_dots.png'),
    // icEdit: require('../assets/images/ic_edit.png'),
    // icLink: require('../assets/images/link.png'),
    // rightArrow: require('../assets/images/right_arrow.png'),
    // icAdd: require('../assets/images/ic_add2.png'),
    // icCamera: require('../assets/images/camera.png'),
    // icCross: require('../assets/images/ic_cross.png'),
    // icHeart: require('../assets/images/activeHeart.png'),
    // icSend: require('../assets/images/ic_send.png'),
    // icChat: require('../assets/images/chatIcon.png'),
    // icGroup: require('../assets/images/icGroup.png'),
    usericon:require('../assets/images/profile.png'),
    searchIcon:require('../assets/images/SearcIcon.png'),
    PressButton:require('../assets/images/press-button.png'),
    DropdownIcon:require('../assets/images/down-arrow.png'),
    Pencil:require('../assets/images/pencil.png'),
    Fiter:require('../assets/images/filter.png'),
    backarrow:require('../assets/images/right-arrow.png'),
    calender:require('../assets/images/calendar.png'),
    tesk:require('../assets/images/checklist.png'),
    Payroll:require('../assets/images/save-money.png'),
    Meal:require('../assets/images/arrow.png'),
    employee:require('../assets/images/user.png'),
    Background:require('../assets/images/Backgroud.png')
  
  };